import { Metadata } from "next";
import "@/styles/global.css";
import Footer from "./(home)/components/footer";
import TopLayout from "./(home)/components/header";
import Sidebar from "./(home)/components/sidebar";

export const metadata: Metadata = {
  title: {
    template: "%s | Next.js",
    default: "Loading...",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <TopLayout />
        <div className="relative flex">
          <Sidebar />
          <div className="ml-56 flex-1 h-[500px] overflow-y-auto">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
